using Assets.Script.Core.Weapon;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UIElements;

public class DefaultData
{
    public static BaseWeapon[] GetBaseWeapons()
    {
        BaseWeapon[] listWeapon = new BaseWeapon[13];

        WeaponEnum.EFireMode[] rifle = new WeaponEnum.EFireMode[2];
        rifle[0] = WeaponEnum.EFireMode.Single;
        rifle[1] = WeaponEnum.EFireMode.Auto;

        WeaponEnum.EFireMode[] sniper = new WeaponEnum.EFireMode[1];
        sniper[0] = WeaponEnum.EFireMode.Single;

        WeaponEnum.EFireMode[] shotgunNew = new WeaponEnum.EFireMode[1];
        shotgunNew[0] = WeaponEnum.EFireMode.Auto;

        WeaponEnum.EFireMode[] shotgunClassic = new WeaponEnum.EFireMode[1];
        shotgunClassic[0] = WeaponEnum.EFireMode.Single;

        BaseWeapon acm = new BaseWeapon();
        acm.Id = "1";
        acm.NameDisplay = "ACM";
        acm.SpritePath = "Sprites/Weapons/Guns/AR/ACM";
        acm.ShellExtractor = new Vector2(0.269f, 0.183f);
        acm.MuzzleExtractor = new Vector2(1.22f, 0.203f);
        acm.BulletSpeed = 1000f;
        acm.AttackDamage = 50f;
        acm.FireRate = 0.1f;
        acm.ReloadTime = 0.5f;
        acm.SpreadAim = 0.1f;
        acm.Mass = 1;
        acm.AmmoMax = 30;
        acm.AmmoCurrent = 30;
        acm.MoveSpeedMultiplier = 1.2f;
        acm.JumpSpeedpMultiplier = 1.5f;
        acm.WeaponType = WeaponEnum.EWeaponType.Rifle;
        acm.AmmoType = WeaponEnum.EAmmoType.Sharp;
        acm.WeaponState = WeaponEnum.EWeaponState.Idle;
        acm.FireMode = rifle;

        BaseWeapon hp416 = new BaseWeapon();
        hp416.Id = "2";
        hp416.NameDisplay = "HP416";
        hp416.SpritePath = "Sprites/Weapons/Guns/AR/HP416";
        hp416.ShellExtractor = new Vector2(0.137f, 0.218f);
        hp416.MuzzleExtractor = new Vector2(1.22f, 0.203f);
        hp416.BulletSpeed = 1000f;
        hp416.AttackDamage = 10;
        hp416.FireRate = 0.1f;
        hp416.ReloadTime = 1f;
        hp416.SpreadAim = 0.1f;
        hp416.Mass = 1;
        hp416.AmmoMax = 30;
        hp416.AmmoCurrent = 30;
        hp416.MoveSpeedMultiplier = 1.2f;
        hp416.JumpSpeedpMultiplier = 1.5f;
        hp416.WeaponType = WeaponEnum.EWeaponType.Rifle;
        hp416.AmmoType = WeaponEnum.EAmmoType.Sharp;
        hp416.WeaponState = WeaponEnum.EWeaponState.Idle;
        hp416.FireMode = rifle;

        BaseWeapon auc = new BaseWeapon();
        auc.Id = "3";
        auc.NameDisplay = "AUCC";
        auc.SpritePath = "Sprites/Weapons/Guns/AR/AUC";
        auc.ShellExtractor = new Vector2(0.137f, 0.218f);
        auc.MuzzleExtractor = new Vector2(0.967f, 0.211f);
        auc.BulletSpeed = 1000f;
        auc.AttackDamage = 10;
        auc.FireRate = 0.1f;
        auc.ReloadTime = 0.25f;
        auc.SpreadAim = 0.1f;
        auc.Mass = 1;
        auc.AmmoMax = 30;
        auc.AmmoCurrent = 30;
        auc.MoveSpeedMultiplier = 1.2f;
        auc.JumpSpeedpMultiplier = 1.5f;
        auc.WeaponType = WeaponEnum.EWeaponType.Rifle;
        auc.AmmoType = WeaponEnum.EAmmoType.Sharp;
        auc.WeaponState = WeaponEnum.EWeaponState.Idle;
        auc.FireMode = rifle;


        BaseWeapon awm = new BaseWeapon();
        awm.Id = "4";
        awm.NameDisplay = "AWN";
        awm.SpritePath = "Sprites/Weapons/Guns/SR/AWN";
        awm.ShellExtractor = new Vector2(0.137f, 0.218f);
        awm.MuzzleExtractor = new Vector2(1.737f, 0.238f);
        awm.BulletSpeed = 2000f;
        awm.AttackDamage = 100;
        awm.FireRate = 0.1f;
        awm.ReloadTime = 0.25f;
        awm.SpreadAim = 0.1f;
        awm.Mass = 1;
        awm.AmmoMax = 5;
        awm.AmmoCurrent = 4;
        awm.MoveSpeedMultiplier = 1.2f;
        awm.JumpSpeedpMultiplier = 1.5f;
        awm.WeaponType = WeaponEnum.EWeaponType.Sniper;
        awm.AmmoType = WeaponEnum.EAmmoType.Sharp;
        awm.WeaponState = WeaponEnum.EWeaponState.Idle;
        awm.FireMode = sniper;

        BaseWeapon ka98 = new BaseWeapon();
        ka98.Id = "5";
        ka98.NameDisplay = "KA98";
        ka98.SpritePath = "Sprites/Weapons/Guns/SR/KA98";
        ka98.ShellExtractor = new Vector2(0.34f, 0.169f);
        ka98.MuzzleExtractor = new Vector2(1.528f, 0.172f);
        ka98.BulletSpeed = 2000f;
        ka98.AttackDamage = 100;
        ka98.FireRate = 0.1f;
        ka98.ReloadTime = 0.25f;
        ka98.SpreadAim = 0.1f;
        ka98.Mass = 1;
        ka98.AmmoMax = 5;
        ka98.AmmoCurrent = 4;
        ka98.MoveSpeedMultiplier = 1.2f;
        ka98.JumpSpeedpMultiplier = 1.5f;
        ka98.WeaponType = WeaponEnum.EWeaponType.Sniper;
        ka98.AmmoType = WeaponEnum.EAmmoType.Sharp;
        ka98.WeaponState = WeaponEnum.EWeaponState.Idle;
        ka98.FireMode = sniper;

        BaseWeapon clock17 = new BaseWeapon();
        clock17.Id = "6";
        clock17.NameDisplay = "Clock 17";
        clock17.SpritePath = "Sprites/Weapons/Guns/HG/Clock17";
        clock17.ShellExtractor = new Vector2(0.062f, 0.218f);
        clock17.MuzzleExtractor = new Vector2(0.387f, 0.203f);
        clock17.BulletSpeed = 500f;
        clock17.AttackDamage = 10;
        clock17.FireRate = 0.1f;
        clock17.ReloadTime = 0.7f;
        clock17.SpreadAim = 0.1f;
        clock17.Mass = 1;
        clock17.AmmoMax = 15;
        clock17.AmmoCurrent = 15;
        clock17.MoveSpeedMultiplier = 1.2f;
        clock17.JumpSpeedpMultiplier = 1.5f;
        clock17.WeaponType = WeaponEnum.EWeaponType.Pistol;
        clock17.AmmoType = WeaponEnum.EAmmoType.Circle;
        clock17.WeaponState = WeaponEnum.EWeaponState.Idle;
        clock17.FireMode = rifle;

        BaseWeapon desertFalcon = new BaseWeapon();
        desertFalcon.Id = "7";
        desertFalcon.NameDisplay = "Desert Falcon";
        desertFalcon.SpritePath = "Sprites/Weapons/Guns/HG/DesertFalcon";
        desertFalcon.ShellExtractor = new Vector2(0.162f, 0.218f);
        desertFalcon.MuzzleExtractor = new Vector2(0.47f, 0.203f);
        desertFalcon.BulletSpeed = 600f;
        desertFalcon.AttackDamage = 20;
        desertFalcon.FireRate = 0.1f;
        desertFalcon.ReloadTime = 0.8f;
        desertFalcon.SpreadAim = 0.1f;
        desertFalcon.Mass = 1;
        desertFalcon.AmmoMax = 7;
        desertFalcon.AmmoCurrent = 7;
        desertFalcon.MoveSpeedMultiplier = 1.2f;
        desertFalcon.JumpSpeedpMultiplier = 1.5f;
        desertFalcon.WeaponType = WeaponEnum.EWeaponType.Pistol;
        desertFalcon.AmmoType = WeaponEnum.EAmmoType.Circle;
        desertFalcon.WeaponState = WeaponEnum.EWeaponState.Idle;
        desertFalcon.FireMode = rifle;

        BaseWeapon n1911 = new BaseWeapon();
        n1911.Id = "8";
        n1911.NameDisplay = "N1911";
        n1911.SpritePath = "Sprites/Weapons/Guns/HG/N1911";
        n1911.ShellExtractor = new Vector2(0.162f, 0.255f);
        n1911.MuzzleExtractor = new Vector2(0.47f, 0.237f);
        n1911.BulletSpeed = 500f;
        n1911.AttackDamage = 10;
        n1911.FireRate = 0.1f;
        n1911.ReloadTime = 0.7f;
        n1911.SpreadAim = 0.1f;
        n1911.Mass = 1;
        n1911.AmmoMax = 15;
        n1911.AmmoCurrent = 15;
        n1911.MoveSpeedMultiplier = 1.2f;
        n1911.JumpSpeedpMultiplier = 1.5f;
        n1911.WeaponType = WeaponEnum.EWeaponType.Pistol;
        n1911.AmmoType = WeaponEnum.EAmmoType.Circle;
        n1911.WeaponState = WeaponEnum.EWeaponState.Idle;
        n1911.FireMode = rifle;

        BaseWeapon venelliM4 = new BaseWeapon();
        venelliM4.Id = "9";
        venelliM4.NameDisplay = "Venelli M4";
        venelliM4.SpritePath = "Sprites/Weapons/Guns/Shotgun/VenelliM4";
        venelliM4.ShellExtractor = new Vector2(0.373f, 0.146f);
        venelliM4.MuzzleExtractor = new Vector2(1.268f, 0.142f);
        venelliM4.BulletSpeed = 500f;
        venelliM4.AttackDamage = 10;
        venelliM4.FireRate = 0.1f;
        venelliM4.ReloadTime = 0.7f;
        venelliM4.SpreadAim = 0.1f;
        venelliM4.Mass = 1;
        venelliM4.AmmoMax = 15;
        venelliM4.AmmoCurrent = 15;
        venelliM4.MoveSpeedMultiplier = 1.2f;
        venelliM4.JumpSpeedpMultiplier = 1.5f;
        venelliM4.WeaponType = WeaponEnum.EWeaponType.Shotgun;
        venelliM4.AmmoType = WeaponEnum.EAmmoType.Round;
        venelliM4.WeaponState = WeaponEnum.EWeaponState.Idle;
        venelliM4.FireMode = shotgunNew;

        BaseWeapon sg686 = new BaseWeapon();
        sg686.Id = "10";
        sg686.NameDisplay = "SG686";
        sg686.SpritePath = "Sprites/Weapons/Guns/Shotgun/SG686";
        sg686.ShellExtractor = new Vector2(0.27f, 0.146f);
        sg686.MuzzleExtractor = new Vector2(1.268f, 0.142f);
        sg686.BulletSpeed = 500f;
        sg686.AttackDamage = 10;
        sg686.FireRate = 0.1f;
        sg686.ReloadTime = 0.7f;
        sg686.SpreadAim = 0.1f;
        sg686.Mass = 1;
        sg686.AmmoMax = 15;
        sg686.AmmoCurrent = 15;
        sg686.MoveSpeedMultiplier = 1.2f;
        sg686.JumpSpeedpMultiplier = 1.5f;
        sg686.WeaponType = WeaponEnum.EWeaponType.Shotgun;
        sg686.AmmoType = WeaponEnum.EAmmoType.Round;
        sg686.WeaponState = WeaponEnum.EWeaponState.Idle;
        sg686.FireMode = shotgunClassic;

        BaseWeapon microUZE = new BaseWeapon();
        microUZE.Id = "11";
        microUZE.NameDisplay = "Micro UZE";
        microUZE.SpritePath = "Sprites/Weapons/Guns/SMG/MicroUZE";
        microUZE.ShellExtractor = new Vector2(-0.097f, 0.175f);
        microUZE.MuzzleExtractor = new Vector2(0.244f, 0.175f);
        microUZE.BulletSpeed = 500f;
        microUZE.AttackDamage = 10;
        microUZE.FireRate = 0.1f;
        microUZE.ReloadTime = 0.7f;
        microUZE.SpreadAim = 0.1f;
        microUZE.Mass = 1;
        microUZE.AmmoMax = 15;
        microUZE.AmmoCurrent = 15;
        microUZE.MoveSpeedMultiplier = 1.2f;
        microUZE.JumpSpeedpMultiplier = 1.5f;
        microUZE.WeaponType = WeaponEnum.EWeaponType.SMG;
        microUZE.AmmoType = WeaponEnum.EAmmoType.Circle;
        microUZE.WeaponState = WeaponEnum.EWeaponState.Idle;
        microUZE.FireMode = rifle;

        BaseWeapon unp45 = new BaseWeapon();
        unp45.Id = "12";
        unp45.NameDisplay = "UNP45";
        unp45.SpritePath = "Sprites/Weapons/Guns/SMG/UNP45";
        unp45.ShellExtractor = new Vector2(0.051f, 0.22f);
        unp45.MuzzleExtractor = new Vector2(0.851f, 0.216f);
        unp45.BulletSpeed = 500f;
        unp45.AttackDamage = 10;
        unp45.FireRate = 0.1f;
        unp45.ReloadTime = 0.7f;
        unp45.SpreadAim = 0.1f;
        unp45.Mass = 1;
        unp45.AmmoMax = 15;
        unp45.AmmoCurrent = 15;
        unp45.MoveSpeedMultiplier = 1.2f;
        unp45.JumpSpeedpMultiplier = 1.5f;
        unp45.WeaponType = WeaponEnum.EWeaponType.SMG;
        unp45.AmmoType = WeaponEnum.EAmmoType.Sharp;
        unp45.WeaponState = WeaponEnum.EWeaponState.Idle;
        unp45.FireMode = rifle;

        BaseWeapon victor = new BaseWeapon();
        victor.Id = "13";
        victor.NameDisplay = "Victor";
        victor.SpritePath = "Sprites/Weapons/Guns/SMG/Victor";
        victor.ShellExtractor = new Vector2(0.351f, 0.185f);
        victor.MuzzleExtractor = new Vector2(0.851f, 0.131f);
        victor.BulletSpeed = 500f;
        victor.AttackDamage = 10;
        victor.FireRate = 0.1f;
        victor.ReloadTime = 0.7f;
        victor.SpreadAim = 0.1f;
        victor.Mass = 1;
        victor.AmmoMax = 15;
        victor.AmmoCurrent = 15;
        victor.MoveSpeedMultiplier = 1.2f;
        victor.JumpSpeedpMultiplier = 1.5f;
        victor.WeaponType = WeaponEnum.EWeaponType.SMG;
        victor.AmmoType = WeaponEnum.EAmmoType.Sharp;
        victor.WeaponState = WeaponEnum.EWeaponState.Idle;
        victor.FireMode = rifle;


        listWeapon[0] = acm;
        listWeapon[1] = hp416;
        listWeapon[2] = auc;
        listWeapon[3] = awm;
        listWeapon[4] = ka98;
        listWeapon[5] = clock17;
        listWeapon[6] = desertFalcon;
        listWeapon[7] = n1911;
        listWeapon[8] = venelliM4;
        listWeapon[9] = sg686;
        listWeapon[10] = microUZE;
        listWeapon[11] = unp45;
        listWeapon[12] = victor;
        return listWeapon;
    }
}
